site_name: Artisan Worktables

pages:
  - Introduction: index.md
  - ChangeLog: changelog.md
  - Configuration Files: configuration.md
  - Creating Recipes:
    - Quick Reference: recipes/quickreference.md
    - Getting Started: recipes/gettingstarted.md
    - Basic Recipes: recipes/basic.md
    - Table Tiers: recipes/tiers.md
    - Recipes with Tools: recipes/tools.md
    - Recipes with Fluids: recipes/fluids.md
    - Extra Chance Output: recipes/extraoutput.md
    - Weighted Primary Output: recipes/weighted.md
    - Secondary Ingredients: recipes/secondaryingredients.md
    - Experience Requirements: recipes/experiencerequirements.md
    - GameStages: recipes/gamestages.md
    - Copying Recipes: recipes/copying.md
  - Tools:
    - Custom Tool Materials: tools/custommaterials.md
  - Developer Notes:
    - Workflow: notes/workflow.md

theme: readthedocs

markdown_extensions:
  - admonition