site_name: Artisan Worktables

pages:
  - Introduction: index.md
  - ChangeLog: changelog.md
  - Toolbox: toolbox.md
  - Design Pattern: designpattern.md
  - Mod Integrations: integrations/index.md
  - Slot-Locking: slotlocking.md
  - Creating Recipes:
    - Quick Reference: recipes/quickreference.md
    - Creative Tools: recipes/creativemode.md
    - Getting Started: recipes/gettingstarted.md
    - Basic Recipes: recipes/basic.md
    - Recipe Names: recipes/names.md
    - Table Tiers: recipes/tiers.md
    - Recipes with Tools: recipes/tools.md
    - Recipes with Fluids: recipes/fluids.md
    - Extra Chance Output: recipes/extraoutput.md
    - Weighted Primary Output: recipes/weighted.md
    - Secondary Ingredients: recipes/secondaryingredients.md
    - Experience Requirements: recipes/experiencerequirements.md
    - Hiding Recipes: recipes/hiding.md
    - Copying Recipes: recipes/copying.md
    - Recipe Functions: recipes/functions.md
  - Tools:
    - Custom Tool Materials: tools/custommaterials.md
  - Development:
    - Contributor's License Agreement: cla.md
    - Workflow: notes/workflow.md

theme: readthedocs

markdown_extensions:
  - admonition